# Generated by Django 5.2.4 on 2025-07-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Mindfulness', 'Mindfulness'), ('Sleep', 'Sleep'), ('Anxiety', 'Anxiety'), ('Breathing', 'Breathing')], default='Mindfulness', max_length=50),
        ),
    ]
